### ISSUE TITLE
客户端问题

### ISSUE THREAD

**Issue by stormphper** [xiaojiaqi/10billionhongbaos#1]
请问客户端是单独一台服务器吗

**Comment by xiaojiaqi** [comment]
根据你的测试强度来，如果最简单的测试 你只模拟几千个客户端，那么完全可以和服务器在同一台服务器上运行，如果你希望模拟几万个 或者几十万个客户端，那么你需要单独的一台 或者多台服务器。在我的测试里，我使用了17台独立主机模拟客户端。
